// Register Problem
export const REGISTER_PROBLEM = "REGISTER_PROBLEM";
export const REGISTER_PROBLEM_LOADING = 'REGISTER_PROBLEM_LOADING';
export const REGISTER_PROBLEM_SUCCESS = 'REGISTER_PROBLEM_SUCCESS';

// Register Account
export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";
export const REGISTER_ACCOUNT_LOADING = 'REGISTER_ACCOUNT_LOADING';
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';

// Login Account
export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGIN_ACCOUNT_LOADING = 'LOGIN_ACCOUNT_LOADING';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';



