// Register Problem
export const REGISTER_PROBLEM_LOADING = 'REGISTER_PROBLEM_LOADING';
export const REGISTER_PROBLEM_SUCCESS = "REGISTER_PROBLEM_SUCCESS";
export const GET_PROBLEM_SUCCESS = "GET_PROBLEM_SUCCESS";


// Register Account
export const REGISTER_ACCOUNT = "REGISTER_ACCOUNT";
export const REGISTER_ACCOUNT_LOADING = 'REGISTER_ACCOUNT_LOADING';
export const REGISTER_ACCOUNT_SUCCESS = 'REGISTER_ACCOUNT_SUCCESS';

// Login Account
export const LOGIN_ACCOUNT = "LOGIN_ACCOUNT";
export const LOGIN_ACCOUNT_LOADING = 'LOGIN_ACCOUNT_LOADING';
export const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';

// Register Task
export const REGISTER_TASK = "REGISTER_TASK";
export const REGISTER_TASK_LOADING = 'REGISTER_TASK_LOADING';
export const REGISTER_TASK_SUCCESS = 'REGISTER_TASK_SUCCESS';

export const GET_TASKS = "GET_TASKS";
export const GET_TASKS_LOADING = 'GET_TASKS_LOADING';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';


export const GET_MYTASKS = "GET_MYTASKS";
export const GET_MYTASKS_LOADING = 'GET_MYTASKS_LOADING';
export const GET_MYTASKS_SUCCESS = 'GET_MYTASKS_SUCCESS';

export const GET_TASKS_ADMIN = "GET_TASKS_ADMIN";
export const GET_TASKS_LOADING_ADMIN = 'GET_TASKS_LOADING_ADMIN';
export const GET_TASKS_SUCCESS_ADMIN = 'GET_TASKS_SUCCESS_ADMIN';

export const GET_TASKS_VOLUNTEER = "GET_TASKS_VOLUNTEER";
export const GET_TASKS_LOADING_VOLUNTEER = 'GET_TASKS_LOADING_VOLUNTEER';
export const GET_TASKS_SUCCESS_VOLUNTEER = 'GET_TASKS_SUCCESS_VOLUNTEER';

export const TAKE_TASK_LOADING = 'TAKE_TASK_LOADING';
export const TAKE_TASK_SUCCESS = 'TAKE_TASK_SUCCESS';




